<br /><br />
<div class='row padding20 text-white relative' style="width: 95%; left: 3.5%">
	<?php
    	echo"<div class='col-lg-12 padding0'>";
			echo"<nav aria-label='breadcrumb'>";
  				echo"<ol class='breadcrumb'>";
    				echo"<li class='breadcrumb-item'><a href='".$url."usuario'>Usuários</a></li>";
    				echo "<li class='breadcrumb-item active' aria-current='page'>Detalhes</li>";
    			echo "</ol>";
			echo"</nav>";
		echo "</div>";
    ?>
	<?php
		echo "<div class='col-lg-12 background_dark'>";
			echo"<a href='javascript:window.history.go(-1)' class='padding' title='Voltar'>";
				echo"<span class='glyphicon glyphicon-arrow-left text-white' style='font-size: 25px;'></span>";
			echo"</a>";
			echo "<br />";
			echo "<br />";
			echo "<div class='table-responsive'>";
				$this->load->view("usuario/_detalhes",$obj);
				echo "<p> Dados do cliente </p>";
                echo "<table class='table table-striped table-hover text-white'style='margin-bottom: 0px;'>";
                    echo "<tr>";
                        echo "<td style='width: 30%;'>";
                            echo "CPF";
                        echo "</td>";
                        echo "<td class='text-left'>";
                            echo $obj_cliente->Cpf;
                        echo "</td>";
                    echo "</tr>";
                    echo "<tr>";
                        echo "<td style='width: 30%;'>";
                            echo "Celular";
                        echo "</td>";
                        echo "<td class='text-left'>";
                            echo $obj_cliente->Celular;
                        echo "</td>";
                    echo "</tr>";
                    echo "<tr>";
                        echo "<td style='width: 30%;'>";
                            echo "Telefone";
                        echo "</td>";
                        echo "<td class='text-left'>";
                            echo $obj_cliente->Telefone;
                        echo "</td>";
                    echo "</tr>";
                echo "</table>";
                echo "<p>Endereço do cliente </p>";
                echo "<table class='table table-striped table-hover text-white'style='margin-bottom: 0px;'>";
                    echo "<tr>";
                        echo "<td style='width: 30%;'>";
                            echo "Rua";
                        echo "</td>";
                        echo "<td class='text-left'>";
                            echo $obj_endereco->Rua;
                        echo "</td>";
                    echo "</tr>";
                    echo "<tr>";
                        echo "<td style='width: 30%;'>";
                            echo "Cidade";
                        echo "</td>";
                        echo "<td class='text-left'>";
                            echo $obj_endereco->Cidade;
                        echo "</td>";
                    echo "</tr>";
                    echo "<tr>";
                        echo "<td style='width: 30%;'>";
                            echo "Bairro";
                        echo "</td>";
                        echo "<td class='text-left'>";
                            echo $obj_endereco->Bairro;
                        echo "</td>";
                    echo "</tr>";
                    echo "<tr>";
                        echo "<td style='width: 30%;'>";
                            echo "Número";
                        echo "</td>";
                        echo "<td class='text-left'>";
                            echo $obj_endereco->Numero;
                        echo "</td>";
                    echo "</tr>";
                    echo "<tr>";
                        echo "<td style='width: 30%;'>";
                            echo "Complemento";
                        echo "</td>";
                        echo "<td class='text-left'>";
                            echo $obj_endereco->Complemento;
                        echo "</td>";
                    echo "</tr>";
                echo "</table>";
			echo "</div>";
		echo "</div>";
	?>
</div>